### ISSUE TITLE
Exception on return await

### ISSUE THREAD

**Issue by jnyrup** [u2uconsult/codeanalyzers#20]
Given this code 
```csharp
public async Task GetTaskAsync()
{
	Task a = Task.FromResult(0);
	Task b = Task.FromResult(1);
	Task[] tasks = new[] { a, b };

	return await Task.WhenAll(tasks);
}
```

When I place the cursor on `await` and press `ctrl + .` I get the following exception:

```csharp
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Extensions.ITypeSymbolExtensions.GenerateTypeSyntax(INamespaceOrTypeSymbol symbol,Boolean nameSyntax)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.TypeExpression(ITypeSymbol typeSymbol)
   at U2UConsult.CodeAnalyzers.Performance.AwaitTasksCorrectlyCodeFixProvider.MakeNewBlock(Document document,BlockSyntax block,ITypeSymbol returnType)
   at async U2UConsult.CodeAnalyzers.Performance.AwaitTasksCorrectlyCodeFixProvider.MakeNewSyntax(<Unknown Parameters>)
   at async U2UConsult.CodeAnalyzers.Performance.AwaitTasksCorrectlyCodeFixProvider.MakeNewMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by KrisVandermotten** [comment]
Thanks for reporting. This is fixed in version 2.15.2.
