### ISSUE TITLE
ArgumentNullException from InitializedLocalsShouldBeUsedAnalyzer

### ISSUE THREAD

**Issue by jnyrup** [u2uconsult/codeanalyzers#25]
While refactoring I had this piece of code
```c#
using System.IO;

namespace TestProject
{
    static class MyClass
    {
        public static byte[] ReadAsBytesAsync(this Stream input)
        {
            byte[] buffer = null;
            await input.ReadAsync(buffer, 0, 0);
        }
    }
}
```

When changing the return type from `byte[]` to `Task<byte[]>` I got the following exception:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'U2UConsult.CodeAnalyzers.Performance.InitializedLocalsShouldBeUsedAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: key'.	UnitTestProject19		1	Active	Analyzer 'U2UConsult.CodeAnalyzers.Performance.InitializedLocalsShouldBeUsedAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: UnitTestProject19
SyntaxTree: C:\Users\jonas\source\repos\UnitTestProject19\UnitTestProject19\UnitTest1.cs
SyntaxNode: { byte[] buffer = null; await input ... [BlockSyntax]@[164..261) (7,8)-(10,9)

System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at U2UConsult.CodeAnalyzers.Performance.InitializedLocalsShouldBeUsedAnalyzer.BlockAnalysis.AnalyzeVariableDeclarator(VariableDeclaratorSyntax variable)
   at U2UConsult.CodeAnalyzers.Performance.InitializedLocalsShouldBeUsedAnalyzer.BlockAnalysis.AnalyzeLocalDeclarationStatement(LocalDeclarationStatementSyntax declarationStatement)
   at U2UConsult.CodeAnalyzers.Performance.InitializedLocalsShouldBeUsedAnalyzer.BlockAnalysis.AnalyzeStatement(StatementSyntax statement)
   at U2UConsult.CodeAnalyzers.Performance.InitializedLocalsShouldBeUsedAnalyzer.BlockAnalysis.AnalyzeStatements()
   at U2UConsult.CodeAnalyzers.Performance.InitializedLocalsShouldBeUsedAnalyzer.AnalyzeBlock(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__50`1.<ExecuteSyntaxNodeAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by KrisVandermotten** [comment]
Thanks for reporting this bug. It has been fixed in version 2.18.2, available for download now.
